
  // This file is automatically generated by scripts/tokens/app.mjs!
  // It contains a snippet to update Figma variable syntax and descriptions via the Figma Plugin API.
  // To use, copy the contents of this file and run it in the Figma console (F12) on a file with the relevant variables.
  // Make sure to run it in a file that has the variables already created, otherwise it won't find them.
  // You can get the variable IDs by inspecting the variable in Figma and looking at the URL (the part after "variables/").

  Promise.all([
  ["VariableID:101:1595", "var(--msd-color-text-secondary-enabled)", ""],
  ["VariableID:61:588", "var(--msd-color-surface-secondary-enabled)", ""],
  ["VariableID:61:589", "var(--msd-color-surface-secondary-hovered)", ""],
  ["VariableID:61:595", "var(--msd-color-surface-tertiary-hovered)", ""],
  ["VariableID:61:596", "var(--msd-color-surface-tertiary-enabled)", ""],
  ["VariableID:70:600", "var(--msd-color-text-primary-enabled)", ""],
  ["VariableID:70:602", "var(--msd-color-fill-brand-enabled)", ""],
  ["VariableID:70:603", "var(--msd-color-text-on-fill-brand-enabled)", ""],
  ["VariableID:73:604", "var(--msd-color-fill-primary-enabled)", ""],
  ["VariableID:73:605", "var(--msd-color-fill-secondary-enabled)", ""],
  ["VariableID:73:606", "var(--msd-color-fill-tertiary-enabled)", ""],
  ["VariableID:73:607", "var(--msd-color-fill-tertiary-hovered)", ""],
  ["VariableID:85:611", "var(--msd-color-border-brand-enabled)", ""],
  ["VariableID:85:638", "var(--msd-color-border-primary-enabled)", ""],
  ["VariableID:85:643", "var(--msd-color-border-secondary-enabled)", ""],
  ["VariableID:90:1578", "var(--msd-color-fill-brand-hovered)", ""],
  ["VariableID:96:1580", "var(--msd-color-background-enabled)", ""],
  ["VariableID:96:1584", "var(--msd-color-border-tertiary-enabled)", ""],
  ["VariableID:96:1585", "var(--msd-color-text-on-fill-primary-enabled)", ""],
  ["VariableID:96:1586", "var(--msd-color-text-on-fill-secondary-enabled)", ""],
  ["VariableID:96:1587", "var(--msd-color-text-on-fill-tertiary-enabled)", ""],
  ["VariableID:9:74", "var(--msd-color-surface-primary-enabled)", ""],
  ["VariableID:58:573", "var(--msd-color-brand-50)", ""],
  ["VariableID:58:574", "var(--msd-color-brand-100)", ""],
  ["VariableID:58:575", "var(--msd-color-brand-200)", ""],
  ["VariableID:58:576", "var(--msd-color-brand-300)", ""],
  ["VariableID:58:577", "var(--msd-color-brand-400)", ""],
  ["VariableID:58:578", "var(--msd-color-brand-500)", ""],
  ["VariableID:58:579", "var(--msd-color-brand-600)", ""],
  ["VariableID:58:580", "var(--msd-color-brand-700)", ""],
  ["VariableID:58:581", "var(--msd-color-brand-800)", ""],
  ["VariableID:58:582", "var(--msd-color-brand-900)", ""],
  ["VariableID:58:583", "var(--msd-color-brand-950)", ""],
].map(async ([variableId, webSyntax, description]) => {
  const variable = await figma.variables.getVariableByIdAsync(variableId);
  if (variable) {
    variable.setVariableCodeSyntax("WEB", webSyntax);
    variable.description = description;
  }
  return;
})).then(() => console.log("DONE!")).catch(console.error)